### ISSUE TITLE
Shearwater Peregrine no longer downloads to desktop or mobile

### ISSUE THREAD

**Issue by snowmp** [Subsurface-divelog/subsurface#3329]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I've been using Subsurface for the last few months, desktop, laptop and mobile. I have never been able to upload from my Shearwater Peregrine via Bluetooth to my desktop or laptop via Subsurface; however, I've always been able to work around this by uploading to Subsurface mobile, uploading to the cloud, and then downloading from the cloud to laptop or desktop to edit and finish my logs. I really like Subsurface and switched to it from Shearwater Desktop Cloud because it is more complete and has a better user interface, even though Shearwater Desktop Cloud reliably syncs with my Peregrine via Bluetooth. I noticed starting roughly 48 hours ago that my Peregrine no longer uploads to Subsurface mobile. Not sure if this is an issue with Subsurface, Bluetooth, Shearwater or all of the above, but thought I'd flag it here: I believe something has changed and it appears to be quite recent. I'm currently working around by syncing to Shearwater Desktop Cloud, exporting each log in UDDF, and then importing that to Subsurface and renumbering. Any thoughts? Thanks so much for your attention to this and for all you do!

### Operating system:
Windows 10, Samsung NP940Z5L
Android, Kyocera E6910

### Subsurface version:
Subsurface 5.0.3
Subsurface mobile 5.0.3.41

**Comment by DarrellH89** [comment]
I have the same issue with a Galaxy S21 5G, SM-G991U. I'm using the same versions of Subsurface. Thanks for a great application!
Update: I have never able to connect the Peregrine with my Windows 10 System with either Subsurface or the Shearwater Cloud application. I just tried the Shearwater app on my phone and was able to connect to the dive computer.

**Comment by dirkhh** [comment]
This should be fixed for Subsurface-mobile

Downloads from Windows have always been very hit and miss
