### ISSUE TITLE
Subsurface not responding

### ISSUE THREAD

**Issue by SousaMartins** [Subsurface-divelog/subsurface#3330]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Subsurface not responding in one account, but working fine on another account on the same computer. The day before was working in all accounts

### Operating system:
Windows 10 Pro 21H1
Desktop computer

### Subsurface version:
5.0.3
No
Official release

### Current behavior:
Subsurface not responding

**Comment by dirkhh** [comment]
"not responding" is such a strange description of a but.
And of course it's Windows, so who knows...

Can you tell us a little more? Is it not opening a window? Or if it is, what does it show?
If you start it manually from a cmd.exe, are there any messages that would help us understand where it is hanging?

**Comment by SousaMartins** [comment]
Yes it opens a window and it is completely white

![test](https://user-images.githubusercontent.com/53411423/135909919-e1efea16-2472-4e41-986b-0f6de2ee00ac.jpg)

I started it from the desktop shortcut

I uninstall and install the application twice on both accounts and deleted all files from "AppData\Local\Subsurface" and "AppData\Roaming\Subsurface

![TaskManager](https://user-images.githubusercontent.com/53411423/135911076-3b10b787-8eb6-4b01-9db9-8bce6dcb4fbc.jpg)

When run it from the cmd window I get the following message:
QObject::connect(QQuickWindow, QDeclarativeGeoMap_QML_6): invalid nullptr parameter

**Comment by dirkhh** [comment]
hmm, interesting. Not something that I have seen recently.
If you open a `cmd.exe` and cd to `C:\Program Files\Subsurface` and run subsurface.exe from the cmd.exe - is there anything interesting in the output?

**Comment by SousaMartins** [comment]
![cmd](https://user-images.githubusercontent.com/53411423/135914331-a2849218-0210-4ba8-8a67-7d7d081b47fd.jpg)

Running the subsurface.exe from a cmd window opens the same white window saying (Not Responding).

**Comment by dirkhh** [comment]
if you now hit Ctrl-C in that cmd.exe and then grab the two log files in `C:\Users\Home\AppData\Roaming\Subsurface` : `subsurface_out.log` and `subsurface_err.log` that hopefully will tell us what's happening

**Comment by SousaMartins** [comment]
The two files are empty.

**Comment by dirkhh** [comment]
UGH.
That sucks. So we don't even get to write the initial messages out.

No idea what's going on... and almost impossible to debug from here :(

**Comment by SousaMartins** [comment]
How can I debug the app?
I do not have the code.

**Comment by dirkhh** [comment]
debugging on Windows is beyond painful as we have no native tool chain that supports Windows and running things under the debugger is near impossible.
Frustrating as this answer may be - I don't have a better one.

Something sends Subsurface into an infinite loop or some other issue that causes it to freeze... a silly (but often useful) thing to try would be to use one of the latest test builds and see if the problem persists - because if it is caused by an access to uninitialized memory, then using a different build is often a useful temporary workaround.
A recent test build would be here: https://subsurface-divelog.org/downloads/test/subsurface-5.0.3-42-g41258647d232.exe

**Comment by SousaMartins** [comment]
I solved the problem restoring the system to a previous point before the problem raised.

I believed it was a windows "thing".

Thanks for the support
