### ISSUE TITLE
Android build ignores Trusted User Certificates - Let's Encrypt based issue

### ISSUE THREAD

**Issue by GregH-GH** [Subsurface-divelog/subsurface#3335]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
On older android handsets that do not include the newest Let's Encrypt root certificate the app is failing to connect to cloud storage to download / upload the dive list.

Even if the latest certs are installed on the device they are not recognized by SubSurface

### Operating system:
Android 7 on an LG V20

### Subsurface version:
Latest Android Mobile app

### Steps to reproduce:
Run the app on an older mobile handset and the cloud sync no longer works

### Current behavior:
Run the app on an older mobile handset and the cloud sync no longer works

### Expected behavior:
Cloud sync should work if the newer root certs have been added to the device

### Additional information:
What I've found is:

I have both the latest ISTR and R3 certs installed, they are in the Trusted Credentials, but as User creds not System creds.
I can browse to and log in at https://cloud.subsurface-divelog.org/user/xxxxxxxx/dives.html on my phone, using the chrome browser, both on and off my local wifi.
Subsurface does NOT let me login, tried both wifi and data.

What I have also found is that android apps on Android 7 + do NOT by default trust certs in the User store, but apps can choose to by adding a suitable Network security configuration file.

Details and more info can be found here if you are interested.
https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html - User-added CAs
https://developer.android.com/training/articles/security-config 

It also appears that it *might* be possible to add the latest certs to the System creds on a phone, but that requires rooting the phone and then jumping through some more hoops, and rooting the phone then disables a number of other apps, so not really an option to can consider.

If you fancy adding a  suitable Network security configuration file to SubSurface you might make some older phone owners very happy :-)

**Comment by GregH-GH** [comment]
Add a new file \subsurface\android-mobile\res\xml\network_security_config.xml
Contents:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
			<certificates src="system" />
			<certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

Update existing file \subsurface\android-mobile\AndroidManifest.xml
In the <application node add this attribute:
android:networkSecurityConfig="@xml/network_security_config"

**Comment by dirkhh** [comment]
Interesting - way, way, way outside of my practical knowledge of Android development.
I need to see if one of my ancient phones actually can reproduce the error (so that in turn I can evaluate the fix). I don't think I still have anything that's running Android 7, though

**Comment by GregH-GH** [comment]
Hi Dirk,

I've raised an issue on GitHub, and added a comment with what I believe the fix is.

I'm quite happy to side load a test build on my phone if that helps

Cheers

Greg

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by dirkhh** [comment]
>. I'm quite happy to side load a test build on my phone if that helps 

The latest beta build (available on Google Play via the beta channel) includes your proposed fix

**Comment by GregH-GH** [comment]
Good Morning Dirk (Here in the UK at least :-) )

I've tried the beta version, seems to work absolutely fine.

I'm looking at my full list of dives on my old Android 7 phone, yay :-D

Cheers

Greg.
