### ISSUE TITLE
Missing code signature in MacOS version 5.0.4

### ISSUE THREAD

**Issue by suschizu** [Subsurface-divelog/subsurface#3337]
I've received a warning that the code signature in version 5.0.4 is missing (expected: Dirk Hohndel)- can you confirm that? 
Thanks!

**Comment by dirkhh** [comment]
Which binary. Filename?
Where did you download it from?
What's the md5 of that binary?

**Comment by suschizu** [comment]
> Where did you download it from?
I took the download url from the homebrew cask file:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/subsurface.rb

so this is the download (https://subsurface-divelog.org/downloads/Subsurface-5.0.4-10.15+11.0.dmg)

**Comment by dirkhh** [comment]
Thanks - that binary should have been signed, I recreated it from scratch and verified that it is signed.

**Comment by suschizu** [comment]
Great thanks - the code signature is valid :D
