### ISSUE TITLE
Ascent rate

### ISSUE THREAD

**Issue by PlongeurSDF** [Subsurface-divelog/subsurface#3360]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

**Comment by PlongeurSDF** [comment]
is it possible to implement an ascent rate curve like DiversDiary 


![](https://www.plongeur.com/forums/uploads/monthly_2021_12/image.png.a45b70334ee9a2370ba03e839b85c4de.png)

**Comment by atdotde** [comment]
Do you realise this information is in the color of the depth profile line? It is described in the user manual here: https://subsurface-divelog.org/documentation/subsurface-4-user-manual/#S_DiveProfile

Please also note that even in the plot you show, there are only a few possible values: This comes about as there is a depth sample only every few seconds (the exact number depending on the dive computer) and often enough (I don't know about Mares) also the possible depths come in quite large steps (for example for my Suunto computers, depths are always integer multiples of 30cm/1ft).

From the plot I guess there is one depth sample every 10 seconds. Even if you ascent with the largest velocity you encounter which with 15m/min is quite fast, this is 2.5m / 10sec, so there aren't too many possible depth differences in a 10 sec interval.

I will therefore close this request but feel free to reopen it if you want to add something.

**Comment by PlongeurSDF** [comment]
Yes I know,

Sorry for my bad English.
I’m a diver instructor in France.
A very important exercice for level 2, 3, 4 and Instructor, is « assisted ascent for a diver in distress ».
But we have a target for the ascent rate. And the curve is very good information for the interns.

In the past, I used DiversDiary for Marès. But the software no longer exist.

On the forum French plongeur.com <http://plongeur.com/>, we have talking about Subsurface and a new development.

We thought it would have been a good idea.

Best regards,

Jean-Christophe DEGRAS
+33 6 72 47 50 00
***@***.***

**Comment by atdotde** [comment]
Hmm, I don't think the information from the dive computer is useful for this when computed between sample points. If you want more detailed information than the "the line is at most yellow, so we are fine and under 10m/min" you could use the numerical vertical velocity that is shown in information box. But I think it is better to use the ruler (see https://subsurface-divelog.org/documentation/subsurface-4-user-manual/#_the_profile_toolbar ) for a longer time interval like 10m of ascent or so as that has much fewer noise.

**Comment by PlongeurSDF** [comment]
For an example, 

Here is two examples of an analysis I did for students 
Thanks,

**Comment by atdotde** [comment]
<img width="746" alt="Screenshot 2021-12-05 at 23 40 20" src="https://user-images.githubusercontent.com/863957/144766756-71330a37-6f2c-4458-90bc-e0354ae318dc.png">
I think you wanted to attach an image but it did not appear. So here is one from my log. You can see that during the period measured by the ruler, I ascended on average by 3.72 m/min.

**Comment by PlongeurSDF** [comment]
Thanks,

You can see my exemple with this link 
https://drive.google.com/drive/folders/1Nu-kfoVzEMXZSwTmR2QDV-drk8RijXKG?usp=sharing <https://drive.google.com/drive/folders/1Nu-kfoVzEMXZSwTmR2QDV-drk8RijXKG?usp=sharing>

Best regards
