### ISSUE TITLE
add field for dive operator separate from dive site

### ISSUE THREAD

**Issue by tdyas** [Subsurface-divelog/subsurface#3366]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [X] New feature request
- [ ] Discussion request

### Issue long description:
I find myself having to put the dive operator (for boat dives) into the "Notes" field of a dive if I have the "Location" as the actual dive site. It would be useful to have a field for dive operator (boat dock etc.) that could be displayed on the map just like dive sites. It would also allow organizing dives by dive operator.

If there is interest in this feature, I am willing to implement it, but would need the ability to ask questions of the developers so that I may learn the code base.

**Comment by dirkhh** [comment]
There are countless requests just like this. Add a field to track XYZ.
If we followed them, the UI would be a chaotic, unusable mess. Frankly, I think we already added too many of these fields.

But realistically, between the tags and the notes you can track any conceivable information about your dives.
