### ISSUE TITLE
Feature Request: A more comprehensive equipment log

### ISSUE THREAD

**Issue by LouiseMcMahon** [Subsurface-divelog/subsurface#3372]
### Describe the issue:
- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
As a technical cave diver, one day I can be in a drysuit, heated undersuit, a twinset, a bunch of stages and a scooter. The next day I could be diving in a 7/5 wetsuit, no fins or wing and a pair of side-mounted 3L cylinders or anything in between. With so many possible configurations the small suit box becomes quite onerous and the autocomplete is next to useless.

What I would like is more sections in the equipment area for 

- Suit
- Undersuit
- Gloves
- Hood
- Config (ie what wing, harness, backplate, rebreather etc)
- Extra/Notes (This  would be for anything extra ie scooters, secondary rebreathers, extra lighting etc, things that 99.9% of people won't need a special box for)

Having these are their own areas rather than putting them all in the suit or notes section would firstly make auto-complete more useful and allow users to search for previous dives in the same config. Being able to search and then check what weighting was used would be very useful as for me that's a large part of having a log book, so I can get it right every time even if I haven't used that config for a while.

**Comment by dirkhh** [comment]
The UI is crowded and complicated already. And every sub-group of divers has their own desires for things that should be easy to track. In the end the developers need to maintain a UI that tries to be reasonable for most of the very large user base. And the number of our users that actually would care about all the details that you are looking for is miniscule.

Once again, my suggestion would to use tags and notes to save the data that **you** care about the most.
