### ISSUE TITLE
Feature Request: Log visibility in absolutes

### ISSUE THREAD

**Issue by LouiseMcMahon** [Subsurface-divelog/subsurface#3373]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
I would like to be able to log the visibility in absolute terms (meters or feet). What is 1 star to one person maybe 5 stars to another depending on their experience and normal diving locations. When sharing your logbook with others star ratings are meaningless.

**Comment by dirkhh** [comment]
This has been discussed a few times over the years and the consensus has been that most users aren't able to really judge the true visibility - and that on many dives visibility changes dramatically depending on depth or other influences. So we settled on a rating how "good" visibility is.
You are of course able to add your absolute visibility measurement either in the notes or via tags.
