### ISSUE TITLE
Unable to edit tanks and gas mixes in the planner.

### ISSUE THREAD

**Issue by glance-** [Subsurface-divelog/subsurface#3375]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Unable to edit tanks and gas mixes in the planner.

When I hit the + sign and a new gas row is added, I can't edit that line. It's just "blank". Subsurface handles it as a air cylinder with your default cylinder size, and gas changes chan be added to air.

Not even the trash can to delete that row 

### Operating system:
Linux, Qt 5.15.2, Ubuntu 20.04

### Subsurface version:
Current master, v5.0.5-173-gf6a1340a2976.

### Steps to reproduce:
Start subsurface, enter the planner, hit the + cylinder button.

### Current behavior:
I can't edit the cylinder row.

### Expected behavior:
I would like to be able to edit the cylinder row to change gasmix and tank size.

### Additional information:
The depth table can be edited, so something's just wrong with the gas table. The initial gas is there, but I just can't edit new lines.

**Comment by glance-** [comment]
Works as expected in v5.0.5

**Comment by glance-** [comment]
Bisected this one down to a40b40ae7a3a6d17b942b62b265d27a3623da4b9

**Comment by glance-** [comment]
@bstoeger Do you have any top of mind ideas on how to fix this?

**Comment by bstoeger** [comment]
I'll look at it by the end of the week.
