### ISSUE TITLE
Feature Request: Move Dive Sites Tab to a separate location or make it a button

### ISSUE THREAD

**Issue by CSRAutomator** [Subsurface-divelog/subsurface#3381]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When I am clicking along the tabs at the top to see the information on my selected dives and I get to the last tab, it deselects all of the dives I have selected because the dive sites list is not dive specific.  It is a completely different type if information page.

I would like to humbly request that this be just a menu selection or perhaps a separate hot button somewhere else on the main page.  It really is a different kind of animal and should not be with the other dive specific information tabs.

### Operating system:

Edition: Windows 10 Pro
Version: 21H1
OS Build: 19043.1348

Self Built Desktop PC

### Subsurface version:

5.0.5

Official Release

### Steps to reproduce:

Just click along the info tabs to see your dive info, then click on the dive sites tab...  poof, you are no longer in dive specific info and you have to reselect your dives once you get back to another tab.

### Current behavior:

clicking dive site tab takes you out of dive info mode and deselects your dives from the list.

### Expected behavior:

Dive site info should be in the menu or on a button, not a tab in the dive specific info tabs.

**Comment by bstoeger** [comment]
Indeed, that's a known issue. Unfortunately, my time is very restricted at the moment.
