### ISSUE TITLE
UEMIS Zürich: Hitting "Retry" after reconnect message will start over at first dive

### ISSUE THREAD

**Issue by Schwaneberg** [Subsurface-divelog/subsurface#3385]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Subsurface requests the user to reconnect the device and click "Retry", if the Uemis Zürich has almost used up all it's memory (answer files) during synchronization.
Unfortunately, this will start over at the first dive.

### Operating system:

Ubuntu 20.04

### Subsurface version:

5.0.6

### Steps to reproduce:

Sync UEMIS with ~50 or more unsynced dives.

### Current behavior:

Going into an infinit loop fs full -> reconnect -> retry -> fs full

### Expected behavior:

resume syncing at the last dive

**Comment by dirkhh** [comment]
none of the developers have access to a working Uemis Zürich anymore. At this point I would consider the support for this device "likely broken, no longer actively supported" - unless another developer starts working on it.

**Comment by dirkhh** [comment]
should be fixed now :)
Again, thanks
