### ISSUE TITLE
[EXPERIMENTAL] dive master -> dive guide #3389 WHY? Please Regress.

### ISSUE THREAD

**Issue by Fixer-11** [Subsurface-divelog/subsurface#3435]
Just updated from 5.06 to 5.08 and find that my log now makes no sense.

All of my dives (368) have a single person who manages that dive - the Dive Master.
We do not have a dive guide unless we go on a specific trip that has a guide (say when on a live aboard trip).

Can I ask that this change be reversed - or you provide a means of replacing the text used for this field.
For now I am switching back to 5.06 just in case the 5.07/5.08 updates break something else.

**Comment by dirkhh** [comment]
This is the beauty of open source software. You can build your own version using whichever terminology you want.

The Subsurface team will be working towards more inclusive terminology in our software and move away from the term 'master'.
