### ISSUE TITLE
Feature/Change request: Support MTP devices

### ISSUE THREAD

**Issue by the-moog** [Subsurface-divelog/subsurface#3461]
### Describe the issue:
- [ ] Bug
- [x] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

The Garmin Descent Mk2 (and I expect other dive computers too) does not mount with a drive letter.
Windows sees it as a named device.
Subsurface seems not to use the correct file open API that wouold show and access non-drive letter file systems.

These two open source projects combine to provide the required feature:
- https://github.com/hst125fan/mtpmount  (Very open license)
- https://github.com/dokan-dev/dokany  (MIT license)

The change request would be to update the FAQ to mention the above solution
The feature request would be to merge those two projects into SubSurface, making connecting MTP/PTP devices simple.

See https://superuser.com/a/1724634/134192

**Comment by dirkhh** [comment]
I understand the request for the feature. I disagree with the analysis of what is wrong.

The Mk2 uses the MTP protocol. There are a number of different ways to implement that, and a number of different ways to talk to such dive computers. We are using the same library across Windows, macOS, and Linux (in order for me as the person building all these binaries to stay sane - things are crazy complex as they are). Which means on Windows you need to install a specific driver in order for that to work. As explained in the FAQ.
If you want to mount it with a drive letter, go ahead and do that, and simply enter that drive letter as the connection and Subsurface will do the right thing. Or if that doesn't work for you, then you can copy the files into a different folder and import from that.
So to your feature request I say "no thank you - that's a ton of work for me, for a tiny number of users". Also, I don't believe that the license to mtpmount is something that I can comply with.
To your change request - Windows 10 already has a way to mount MTP devices and access the files on them... and a way to talk to the MTP device. I see now value in adding a third way to achieve the same result.
