### ISSUE TITLE
Cloud: Unknown product version

### ISSUE THREAD

**Issue by jebbgrenham** [Subsurface-divelog/subsurface#3481]
### Describe the issue:
- [x] Bug

### Issue long description:

The server returned the following information:
["You are running an unknown product version 5.0.9.0, latest released version is 5.0.8"]

### Operating system:
nix

### Subsurface version:
5.0.9.0
Does not occur on 5.0.8.0
Official release

**Comment by dirkhh** [comment]
The price you pay for upgrading before I officially released a version... This will change within the next hour...
🤣😎
