### ISSUE TITLE
Shift Dive Times show bad time data

### ISSUE THREAD

**Issue by KimDelmar** [Subsurface-divelog/subsurface#3535]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
The "before" and "shifted" time info shown when using "Shift Dive times" is displayed as time 0:0 (1-Jan-1970). The offset calculation is correct (at least relative to 1-Jan-1970). When applied, the correct time offset *is* applied to the dive. This looks slightly alarming but is actually cosmetic.

### Operating system:
MacOS Monterey 12.6 , MBP M1

### Subsurface version:
5.0.10 official build, (both standard and Qt6 builds)

### Steps to reproduce:
1) Select a dive in a dive log
2) right click, choose "Shift dive times"
3) popup window shows both current and shifted dive start time as "0:0"
4) enter an offset -> shifted time changes to offset based on 1-Jan-1970
5) save offset - new dive start time in log is correct (phew!)

### Current behavior:
Subsurface does not display correct dive start time in the popup window, always 0:0

### Expected behavior:
Actual dive start time should be the basis for the time offset.

### Additional information:
n/a
### Mentions:
n/a

**Comment by dirkhh** [comment]
Hmm. Not good. I can trivially reproduce this. I'll take a look.
Thanks for the report!

**Comment by KimDelmar** [comment]
Thanks Dirk - the fix works fine for me. I would have noticed this much earlier but for a pandemic-induced diving hiatus.
I *always* forget to change the timezone on my dive computer on the first dive.
