### ISSUE TITLE
Dive Data Import Error with RATIO iX3M Easy

### ISSUE THREAD

**Issue by gc-robotics** [Subsurface-divelog/subsurface#3537]
**- [X] Bug**
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
![image](https://user-images.githubusercontent.com/47912248/196415011-b8bcb990-5ef4-4ac3-8ffb-691a24cfcbf1.png)

### Operating system:
Linux UBUNTU 20.04.5 LTS
Gnome 3.36.8
X11

### Subsurface version:
Subsurface 5.0.10

### Steps to reproduce:
Connect Dive Computer
Set cable connection
run Subsurface
Open cloud
Import from computer
...error.

### Current behavior:
Popup error

### Expected behavior:
Successful import

### Subsurface LOGS
Starting download from  "SERIAL"
downloading only new dives
INFO: dev_info: Opening serial device /dev/ttyUSB0

INFO: dev_info: Connecting ...

INFO: dc_device_open error value of 0
INFO: dev_info: Starting import ...

[0.313238] ERROR: Received NAK packet with error code 30. [in divesystem_idive.c:355 (divesystem_idive_packet)]
INFO: dev_info: No new dives downloaded from dive computer

Finishing download thread: "Dive data import error"

### Additional Logs

Subsurface: v5.0.10, built with libdivecomputer v0.8.0-devel-Subsurface-NG (565bb2af027011101e9c4e840a8f49162ea4a752)
[0.000000] INFO: Open: name=/dev/ttyUSB0
[0.000918] INFO: Configure: baudrate=115200, databits=8, parity=0, stopbits=0, flowcontrol=0
[0.001029] INFO: Timeout: value=1000
[0.001035] INFO: Sleep: value=300
[0.301192] INFO: Purge: direction=3
[0.308606] INFO: Write: size=6, data=550210ED0C2E
[0.308645] INFO: Read: size=1, data=55
[0.308656] INFO: Read: size=1, data=03
[0.308667] INFO: Read: size=5, data=103015B8D7
[0.308671] ERROR: Received NAK packet with error code 30. [in divesystem_idive.c:355 (divesystem_idive_packet)]

**Comment by jefdriesen** [comment]
I suspect you have a **Ratio iX3M** model instead of the (older) DiveSystem iDive X3M you selected in the screenshot. Although the names are similar, they use a slightly different communication protocol. You need to select the correct model (or at least from the correct family, and then the actual model will be auto-detected).

**Comment by gc-robotics** [comment]
> I suspect you have a **Ratio iX3M** model instead of the (older) DiveSystem iDive X3M you selected in the screenshot. Although the names are similar, they use a slightly different communication protocol. You need to select the correct model (or at least from the correct family, and then the actual model will be auto-detected).

100% correct. I was selecting DiveSystem as Vendor. I found the right model under Ratio. 
Thanks @jefdriesen.
