### ISSUE TITLE
statistics: blank graph displayed if data range is zero

### ISSUE THREAD

**Issue by KimDelmar** [Subsurface-divelog/subsurface#3544]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
In statistics mode (%T), attempting to plot any quantity that has an constant value in all dives,  results in a blank graph.
Presumably this is because of some difficulty with scaling the axis with the constant data (there's no "range" in this case).

For example, a plot of Date (unbinned) (x-axis) vs Weight (y-axis), where the weight value is constant for all the dives.
x-axis and y-axis are both affected the same way.

I acknowledge that this isnt a very interesting graph, but it is more interesting than mysterious and unexpected blank graph.

### Operating system:
M1 MBP, MacOS Monterey 12.6

### Subsurface version:
5.0.10 official Qt5 build.

### Steps to reproduce:

1) load a logbook, and select some dives that have the same value for all dives, eg "weight"
2) view -> dive statistics, and, restrict to selection
3) set up a graph to plot Date (unbinned) vs Weight
4) graph is blank

### Current behavior:
graph is blank

### Expected behavior:
data should be plotted, and some arbitrary scaling of the afflicted axis should be done (eg +/- 1% ?)

### Additional information:
n/a

**Comment by bstoeger** [comment]
Please check #3557.
