### ISSUE TITLE
Cannot access logbook on mounted ntfs volume

### ISSUE THREAD

**Issue by stumpjr** [Subsurface-divelog/subsurface#3555]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I have a dual boot System, For data exchange i use a ntfs partition that is accessible from Windows and Linux.
This desription is for the Linux side
The partion is mounted with uid and gid.
I can create, write and delete files via cli on this partition as normal user (not root).
It is also possible to create files and folders via nautilus file manager but wirh subsurface the directory where the partition is mounted is not shown.

### Operating system:

Ubuntu 22.04 
Language: German

Acer spin5 notebook

On Windows i can access this partition (represented as drive D:) and it works as expected

### Steps to reproduce:

Windows 5.0.10
Linux 5.0.10
### Current behavior:

Cannot acces logbook on mounted NTFS Volume

### Expected behavior:

Access to Logbook files on mounted NTFS Volume

**Comment by atdotde** [comment]
I cannot see why this should not work. Can you be a bit more specific in at which step it fails? Is there an error message?

**Comment by bstoeger** [comment]
> It is also possible to create files and folders via nautilus file manager but wirh subsurface the directory where the partition is mounted is not shown.

Nautilus is a Gnome app. Do you see files with another Qt app? Where is the partition mounted?

**Comment by stumpjr** [comment]
The partition is mounted on /daten as shon in the hardcopy i sent.
I installed the QT-Creator to have another QT-App, started QT-Creator and went to "File->Open" dialog, here i can Navigate to "/daten" and see the files as well as the subdirectory "SubSurfaceLogbuch"
See appended Hardcopy
![Bildschirmfoto vom 2022-11-16 10-11-38](https://user-images.githubusercontent.com/86099377/202126060-8b74cac4-a94e-43a9-b463-69c2cab4be5b.png)

**Comment by atdotde** [comment]
It would be quite unusual to mount it into the root directory (i.e. /daten) and there is no indication the the Nautilus screenshot that it actually is. A more usual place would for example be /mnt/daten

Could you please open a terminal an show the output of the "df" command?

**Comment by stumpjr** [comment]
I tried different mount points all with the same result.
Here is the result of the df command.
![Bildschirmfoto vom 2022-11-16 12-23-13](https://user-images.githubusercontent.com/86099377/202155447-a803736d-fea6-4f1b-818a-04084bb8e66a.png)

**Comment by atdotde** [comment]
OK, it's indeed /daten. What happens when you do (as normal user, not as root)

ls /daten

or

touch /daten/foo

Does this work or do you get an error message?

**Comment by stumpjr** [comment]
I tried different mount points all with the same result.
Here is the result of the df command.
![Bildschirmfoto vom 2022-11-16 12-23-13](https://user-images.githubusercontent.com/86099377/202155447-a803736d-fea6-4f1b-818a-04084bb8e66a.png)

**Comment by stumpjr** [comment]
I get the content of the directory listed, can also list the content of subdir's
![Bildschirmfoto vom 2022-11-16 12-43-24](https://user-images.githubusercontent.com/86099377/202159987-93a12b21-17fe-456e-8ebf-88a59977c851.png)

**Comment by atdotde** [comment]
And is there an error message if you do 

subsurface /daten/SubSurfaceLogbuch/LogbuchJuergen.ssrf

?

**Comment by stumpjr** [comment]
This are the messages i got. I brought the Terminal to the front for complete view

![Bildschirmfoto vom 2022-11-16 13-11-55](https://user-images.githubusercontent.com/86099377/202165758-169b2196-8a85-4356-8927-25a86555d822.png)

**Comment by atdotde** [comment]
That, I guess, indicates it fails opening the file (rather than parse it). Again, on the shell as the normal user, 

cat  /daten/SubSurfaceLogbuch/LogbuchJuergen.ssrf

Does it show the content of the file or fail with an error message?

**Comment by stumpjr** [comment]
I knew you mention that :-)
I did the cat you wanted, after that i made a working copy also in /daten/SubSurfaceLogbuch, just to show you that read write access is given. I opened the working copy via gvim
![Bildschirmfoto vom 2022-11-16 13-50-36](https://user-images.githubusercontent.com/86099377/202174166-6b34b20a-5967-465f-8b10-044d9d30f08f.png)

**Comment by atdotde** [comment]
And then subsurface opens the local copy I presume...

**Comment by stumpjr** [comment]
No, the working copy is also on /daten/SubSurfaceLogbuch. And the behavior on subsurface is the same. I made this copy just to make sure i do not damage anything when opening the file via a normal editor .
The "cat" has been done on the original file like you wanted to see it.

**Comment by bstoeger** [comment]
How did you install Subsurface?

This could be some virtualization problem. For example, when Ubuntu switched Chromium to Snap, I couldn't access some of my files anymore, because they were in a directory which was deemed "unsafe". That was very annoying and thankfully they fixed it after a year.

**Comment by stumpjr** [comment]
It is a snap install
which subsurface gives 
/snap/bin/subsurface

**Comment by bstoeger** [comment]
Ok, then some misconfiguration(?) of the Snap package would be my guess. Sadly, I don't know the slightest thing about virtualization (except that it tends to break things).

@dirkhh?

**Comment by stumpjr** [comment]
It is a snap install
which subsurface gives 
/snap/bin/subsurface

**Comment by dirkhh** [comment]
Yeah, the Snap doesn't have access to that volume. I'm not sure how to add that to the Snap configuration (I don't use them myself). So either ask in a Snap related forum - or install our native version of the app for Ubuntu...
Sorry about that.

**Comment by stumpjr** [comment]
I tried to compile subsurface on my own but failed miserably with this error.
Project ERROR: Unknown module(s) in QT: location positioning
So i downloaded the Appimage from the website 
1. try copied the AppImage to /daten and started it from there -> works! AND /daten is shown in the file->openLogbook 
2. try copied the AppImage to my homedir -> works also AND /daten is shown in the file->openLogbook 
So i think this has something to do with the snap

**Comment by bstoeger** [comment]
There is also a regular native Ubuntu package:

https://launchpad.net/~subsurface/+archive/ubuntu/subsurface

**Comment by stumpjr** [comment]
Yes this works !
Thank you so much for the support to all of you.
And also many thanks to the developers of the program. I know that you Dirk are one of them.
A lot of my diving friends use subsurface it is extraordinary good

**Comment by stumpjr** [comment]
THANK YOU!!!

**Comment by atdotde** [comment]
Just for completeness: If you google "snap ntfs" you will find that this is a known problem. You can either try to mount the partition into your home directory or do something along the lines of 

sudo snap connect subsurface:removable-media

but none of this seems to solve the problems universally.
