### ISSUE TITLE
macOS crash updating cylinder for multiple dives

### ISSUE THREAD

**Issue by acahir** [Subsurface-divelog/subsurface#3578]
### Describe the issue:

- [X ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Attempting to enter cylinder type on multiple dives at once, app crashes. Updating cylinder on individual dives works. When selecting larger numbers (not always the same, but 100+ consistently crashes, but ~25 has both worked and crashed.

Background: New subsurface install, migrating data from MacDive. Exported all dives into UDDF, imported into Subsurface, then saved to cloud log. 

### Operating system:
macOS Monterey 12.5.1 (English)
iMac 27" 2017 (3.8GHz i5 40GB)

### Subsurface version:
5.0.10

### Steps to reproduce:
1. Select 100+ dives in dive log.
2. On Equipment tab, Cylinder type is empty, select AL80 from pulldown menu.
3. Crash

### Current behavior:
App Crashes

### Expected behavior:
Value would update

### Additional information:
Crash log attached
[subsurface macOS crash log.txt](https://github.com/subsurface/subsurface/files/10539259/subsurface.macOS.crash.log.txt)

**Comment by atdotde** [comment]
I tried to reproduce this but did not manage (5.0.20 on Monterey). Maybe you could describe step two in a bit more detail (when have multiple dives with different cylinders selected the cylinder list in the equipment tab is empty. What I tried was to add an AL80 cylinder to all dives but that worked as expected). Or maybe you could share your logbook with me (helling@atdotde.de) as it might be specific to that.

**Comment by acahir** [comment]
Setup: After importing dives from UDDF file, when I select a dive and view the Equipment tab, there is a cylinder listed in the table, but the "Type" field is blank as shown below (noticed due to missing SAC calculations):

<img width="487" alt="Screen Shot 2023-02-01 at 5 17 12 PM" src="https://user-images.githubusercontent.com/1418251/216176603-af88f310-9c8c-4150-b2d2-33e24707cba2.png">

Step 1: Select all 466 dives.
Step 2a: In equipment tab, click into type field (currently blank) of the existing cylinder.
Step 2b: Select AL80 from pulldown list as shown below; list automatically closes.

<img width="727" alt="Screen Shot 2023-02-01 at 5 17 23 PM" src="https://user-images.githubusercontent.com/1418251/216177038-6cc0a8dd-0c55-405c-807f-f1dd89d49a92.png">

Step 3: Crash

Sending local subsurface xml file to supplied email, though crashes happened with cloud log as well. Will also include orig MacDive UDDF export file if you want it, but figured would save you the time to import them all (took a little bit).

**Comment by atdotde** [comment]
With the uddf file provided by @acahir I can reproduce the crash (and witness extremely long loading times with high CPU load...)

Currently, my debugger set up is broken, so I cannot fully investigate. But so far I understand the following: The crash in in same_cylinder (command_edit.cpp) which is called with a NULL pointer as second argument from line 1205 in the same file (the NULL pointer is a result of get_cylinder(d, index)) and then dereferences that pointer. 

An easy hack would be to add a check to same_cylinder (and same_cylinder_type as well) that returns false when handed a NULL pointer. But I am not familiar enough with that part of the code to confidently do that. 

Any idea @dirkhh or @bstoeger ?

**Comment by dirkhh** [comment]
I'm traveling, I can look at this next week

**Comment by acahir** [comment]
> and witness extremely long loading times with high CPU load...

Not to get off topic, but fyi my initial load was also extremely long. Had nothing to compare it to, so didn't know if it was abnormal.
