### ISSUE TITLE
Ability to log tail weights separate from other backplate weight

### ISSUE THREAD

**Issue by LouiseMcMahon** [Subsurface-divelog/subsurface#3856]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [X] New feature request
- [ ] Discussion request

### Issue long description:
When logging weights, there is no way to differentiate tail weights from V/P weights. As they are both integrated and both backplate

### Current behavior:
The current options are 
- Integrated
- belt
- ankle
- backplate
- clip-on

### Expected behavior:
An additional option of "tail" would suffice to allow users to differentiate between V and Tail weights.

### Additional information:
I appreciate only a small number of people will use this feature, but it would be very useful for those of us who tech dive in different water temps and, therefore, undersuits.

**Comment by PeterZaal** [comment]
I am able to just enter any text for type (although sometimes I have to first enter the weight, and then the new type).
I myself use extra types "v-weight" and "p-weight", so I think this is already possible.

**Comment by LouiseMcMahon** [comment]
🤦 It hadnt occurred to me to try typing in the box.
