### ISSUE TITLE
[planner] pO2 over 1.4 (and 1.6) should show a warning, pO2 should be included in the printout 

### ISSUE THREAD

**Issue by keriati** [Subsurface-divelog/subsurface#3859]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Currently in the planner the max pO2 setting is 2.0. I think that there should be always a visible warning when it is set above 1.4. I would also suggest that the max / current pO2 is always included also on the print version as it is a crucial information.

### Operating system:
Mac OS

### Subsurface version:
5.0.10

### Steps to reproduce:
Do a plan.

### Current behavior:
Planner allows pO2 above 1.6. I don't see any warnings. I can't see the pO2 value on the printout.

### Expected behavior:
Planner show warning for pO2 settings above 1.4. I can see the pO2 value at each stop on the printout.

### Additional information:
N/A

### Mentions:
N/A

**Comment by atdotde** [comment]
The max ppO2 values have sane default values. If the user wants to change that I think that is their problem. We don't want to babysit them. We also allow them to do other things in planning that others might consider dangerous (after all, we let them plan decompression dives to substantial depths. There is a warning in the dive notes if at any point in the dive the ppO2 is higher than what you configured to be the maximal value. But Subsurface is not going to argue with you if you set this warning level too high by yourself.

**Comment by keriati** [comment]
@atdotde Thanks for the answer. What do you think about including the pO2 values in the printout for each stop? (For example the DM5 planner is doing this.)

We had the case now by some divers in the Advanced Nitrox class that an example plan was created that included a pO2 level of 1.9, we spotted it in the class, however it was just a bit concerning that in the resulting printed pdf there was no mention about this dive reaching pO2 of 1.9.

The same plan from DM5 automatically includes at each stop the pO2 values. (however dm5 will not allow values above 1.6)
