### ISSUE TITLE
Ventura 13.3.1 on Mac pro Apple M1 Max with iX3M dive computer

### ISSUE THREAD

**Issue by rgiordani71** [Subsurface-divelog/subsurface#3871]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
iX3M easy pro not able to import log dives because the port where the device is connected is not recognised 
<img width="762" alt="image" src="https://user-images.githubusercontent.com/43099465/234549472-0ec2986c-2d13-4cc0-b957-6f2696660723.png">

### Operating system:

Ventura 13.3.1 on Mac pro Apple M1 Max
iX3M easy pro

### Subsurface version:
5.0.10
### Steps to reproduce:
connect the dive computer on the usb port and try to import the dive logs

### Current behavior:
unable to connect

### Expected behavior:
download the dive logs

**Comment by rgiordani71** [comment]
issue solved

**Comment by mikeller** [comment]
@rgiordani71: In the interest of helping others who might have the same issue and find this, what was the solution?
