### ISSUE TITLE
Desktop: Cylinder Pressure Graph scale is incorrect with multiple cylinders

### ISSUE THREAD

**Issue by mwerle** [Subsurface-divelog/subsurface#3943]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

It appears that the gas pressure graph calculates its scale only using the first cylinder's pressure data.

If you have multiple cylinders, and the second cylinders' pressure range is much larger than the first cylinder, it is not shown at all or only partially rendered on the screen.

The pressure graph scale should be calculated across all cylinders for max/min values.

### Operating system:

Debian GNU/Linux 12, English.

### Subsurface version:

Subsurface 5.0.10

Can't recall this happening on earlier versions of Subsurface, but don't often dive with such disparate tank pressures.

Official release

### Steps to reproduce:

Import a dive with at least 2 tanks having pressure data.

Have the "first" tank have a small pressure range (eg, 70bar -> 40bar)
Have the "second" tank have a large pressure range, or a range outside the first tank. (eg, 200bar -> 80bar)

In this scenario, the pressure for the second tank is not visible at all, or only a small portion.

### Current behavior:

It appears that the pressure scale is only calculated using the first tanks' range.
eg: Tank1 70bar -> 20bar
Tank2 : 200bar -> 80bar

Scale for graphing pressure data: 70bar : 20bar

### Expected behavior:

Expect the scale to be calculated across all tanks.
eg: Tank1 70bar -> 20bar
Tank2 : 200bar -> 80bar

Scale for graphing pressure data: 200bar : 20bar

### Mentions:

[Dive.zip](https://github.com/subsurface/subsurface/files/12081545/Dive.zip)
![Subsurface_pressure_graph_bug](https://github.com/subsurface/subsurface/assets/615724/eb43eac7-78f5-461b-93e8-f580ff55a274)

**Comment by mwerle** [comment]
It appears that this issue is fixed in the current development version - 5.0.10-212-xxxxxx (it would be nice to be able to copy-paste the version number from "Help -> About"..)

[issue_pressure_scale.ssrf.zip](https://github.com/subsurface/subsurface/files/12275159/issue_pressure_scale.ssrf.zip)

**Comment by dirkhh** [comment]
I looked at this in the past and I'm pretty sure you were able to cut and post from that dialogue at some point.
My vague recollection is that it depends on the combination of dialogue type and OS ... But this was years ago

**Comment by mwerle** [comment]
Official released version of Subsurface has the issue, self-compiled version from `master`  works fine.. same settings, same OS.  Will check again when the next official release is out now that I have a dive which can showcase the issue.
