### ISSUE TITLE
Dive mode being changed by selecting trips in filtered view

### ISSUE THREAD

**Issue by kruegerha** [Subsurface-divelog/subsurface#3960]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I'm using an extensive logbook including open and closed circuit dives, all filed under numerous "trips".
To separate OC and CCR, I use a filter, which acts on a specific tag.
When using the filtered view, selecting individual dives, everything seems ok. However, if a "trip" is selected, all dives filed under this trip are surprisingly changed to mode "open circuit" and also the "Warning: edited # dives" appears. Immediately selecting "undo" prevents further damage. Failing to immediately undo this, has the potential to mess up the logbook of unwary users.

### Operating system:
linux

### Subsurface version:
origin/master  97a76a6615f3a4451b3f3d71fd4861ceb0a66f9e
no other versions tested yet

### Steps to reproduce:
I've produced a stripped subset of my logbook, which still reproduces the problem.
open the logbook, browse dives. note the the trip "See" has OC and CCR dives.
Then select filtered view, load filter-set "revo-total", select the trip "See" and note that all dives in this trip have been changed to mode OC.
[testlog.xml.gz](https://github.com/subsurface/subsurface/files/12659299/testlog.xml.gz)

### Expected behavior:
never change dive mode unexpectedly

**Comment by kruegerha** [comment]
In my usage of subsurface this bug is an annoyance. It is still present up to today (commit 4bab38b).
Any ideas where to look for it?  what is the relevant code/source file, event triggered by selecting a "trip"?

**Comment by dirkhh** [comment]
That does seem like a serious issue. I will try to find time to look at this.
Also, @bstoeger - any idea what this could be?

**Comment by bstoeger** [comment]
Can reproduce, will look at this after dinner. Should be easy to debug.

**Comment by dirkhh** [comment]
> Can reproduce, will look at this after dinner. Should be easy to debug.

Awesome. Thanks!

**Comment by bstoeger** [comment]
The stacktrace goes like this:
```
#0  Command::EditMode::EditMode (this=this@entry=0x5555567da870, indexIn=indexIn@entry=0, newValue=newValue@entry=0, 
    currentDiveOnly=currentDiveOnly@entry=false) at /home/bs/src-qt6/subsurface/commands/command_edit.cpp:434
#1  0x00005555558c2a45 in Command::editMode (index=0, newValue=0, currentDiveOnly=currentDiveOnly@entry=false)
    at /home/bs/src-qt6/subsurface/commands/command.cpp:172
#2  0x000055555582667d in TabDiveInformation::diveModeChanged (this=0x555556159c60, index=<optimized out>)
    at /home/bs/src-qt6/subsurface/desktop-widgets/tab-widgets/TabDiveInformation.cpp:385
#3  0x00007ffff55814f3 in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#4  0x00007ffff74a8ee5 in QComboBox::currentIndexChanged(int) () from /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#5  0x00007ffff749f82a in ?? () from /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#6  0x00007ffff74a193f in ?? () from /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#7  0x00007ffff74a202d in QComboBox::setCurrentIndex(int) () from /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#8  0x0000555555826397 in TabDiveInformation::updateMode (this=<optimized out>)
    at /home/bs/src-qt6/subsurface/desktop-widgets/tab-widgets/TabDiveInformation.cpp:379
#9  0x0000555555828c98 in TabDiveInformation::updateData (this=0x555556159c60, currentDive=0x555556bf49f0, currentDC=<optimized out>)
    at /home/bs/src-qt6/subsurface/desktop-widgets/tab-widgets/TabDiveInformation.cpp:230
#10 0x00005555558380ea in MainTab::updateDiveInfo (this=0x555556104cc0, selection=std::vector of length 4, capacity 8 = {...}, 
    currentDiveIn=<optimized out>, currentDCIn=<optimized out>) at /home/bs/src-qt6/subsurface/desktop-widgets/tab-widgets/maintab.cpp:98
#11 0x00005555557eec06 in MainWindow::divesSelected (this=0x555555ffba60, selection=std::vector of length 4, capacity 8 = {...}, 
    currentDive=0x555556bf49f0, currentDC=<optimized out>) at /home/bs/src-qt6/subsurface/desktop-widgets/mainwindow.cpp:330
#12 0x00007ffff558113e in ?? () from /lib/x86_64-linux-gnu/libQt6Core.so.6
#13 0x0000555555737966 in DiveListView::divesSelected (this=this@entry=0x55555642d390, _t1=std::vector of length 4, capacity 8 = {...}, 
    _t2=<optimized out>, _t2@entry=0x555556bf49f0, _t3=<optimized out>, _t3@entry=-1)
    at /home/bs/src-qt6/subsurface/build/desktop-widgets/subsurface_interface_autogen/EWIEGA46WW/moc_divelistview.cpp:345
```

When dives are selected, the InfoTab seems to update all fields, which is obviously not good if multiple dives are selected.

**Comment by dirkhh** [comment]
So that's the ancient and beloved multi dive edit. 
But it should be "if I have multiple dives selected and then edit something, Subsurface is smart about how it edits all the selected dives"

This sounds like the user selected a trip and suddenly dives are edited. That seems very different, no?

**Comment by bstoeger** [comment]
Here's a quick fix:
```
diff --git a/desktop-widgets/tab-widgets/TabDiveInformation.cpp b/desktop-widgets/tab-widgets/TabDiveInformation.cpp
index 58cf7ecd5..e2c64820d 100644
--- a/desktop-widgets/tab-widgets/TabDiveInformation.cpp
+++ b/desktop-widgets/tab-widgets/TabDiveInformation.cpp
@@ -13,6 +13,8 @@
 #include "core/statistics.h"
 #include "core/divelist.h"
 
+#include <QSignalBlocker>
+
 #define COMBO_CHANGED 0
 #define TEXT_EDITED 1
 
@@ -375,8 +377,10 @@ void TabDiveInformation::on_chill_valueChanged(int value)
 void TabDiveInformation::updateMode()
 {
        divecomputer *currentDC = parent.getCurrentDC();
-       if (currentDC)
+       if (currentDC) {
+               QSignalBlocker blocker(ui->diveType); // Don't send signals when updating the combobox
                ui->diveType->setCurrentIndex(currentDC->divemode);
+       }
 }
 
 void TabDiveInformation::diveModeChanged(int index)
```
Not sure how happy I am about that, but it does the job. A fundamental question is: what should the dive mode display if multiple dives are selected? Especially if they have multiple dive modes.

**Comment by dirkhh** [comment]
I'm guessing 'blank' ?

**Comment by bstoeger** [comment]
> I'm guessing 'blank' ?

Yes, sounds reasonable.

**Comment by dirkhh** [comment]
This will be included in the CICD release 5061 - depending on which Linux flavor you use, how you can get that will be somewhat different.

**Comment by kruegerha** [comment]
good work! thank you for fixing this issue!

**Comment by bstoeger** [comment]
Feel free to contact me directly with such issues if I miss the report. Currently I am so busy that I don't look at the issue tracker on a regular basis.
