### ISSUE TITLE
Dive Numbers are not shown if dive is part of a trip

### ISSUE THREAD

**Issue by marcvs** [Subsurface-divelog/subsurface#3988]
### Describe the issue:
- [x] Bug
- [x] Change request

### Issue long description:
Dive numbers are not shown in trips

### Operating system:
- OS: Debian Linux, `subsurface-beta_202310210411-1`
- Laptop

### Subsurface version:
-  `subsurface-beta_202310210411-1`
- provided from you apt repo

### Steps to reproduce:
- add dive to trip
- observe dive number not shown in overview

### Expected behavior:
- show the dive number (as the android app correctly does)

**Comment by The-Lid** [comment]
I am seeing the same problem.

OS: Windows 11
Subsurface version 6.0.5054-CICD-release

Please advise when this has been rectified.

**Comment by dirkhh** [comment]
How about a screen shot?
My guess is that your first column is too narrow.

**Comment by The-Lid** [comment]
OK, I feel a "bit" silly now.  It was the column width, sort of, but all the dive numbers under trips are indented so they're not visible with the default column width.

![Subsurface](https://github.com/subsurface/subsurface/assets/157230889/f495fa45-4a85-462a-8771-9e4e733143dd)

**Comment by dirkhh** [comment]
Arguably that UI could be cleaner - but this all is implemented in the toolkit that we use; I'm not sure how much control we'd even have to change that.

**Comment by PeterZaal** [comment]
Had the same issue after updating Subsurface on Windows, came her to find the solution to make the column wider.
I'm sure this behavior has changed somehow, the indent of the dive number on trips wasn't there before.
