### ISSUE TITLE
Website subsurface-divelog.org is not working.

### ISSUE THREAD

**Issue by FL-Diver** [Subsurface-divelog/subsurface#3993]
Hello,

I am new to Subsurface and wanted to try the logging program. However, the website appears to be down. I am not sure who to contact about this so I posted it here. I apologize if this is wrong.

C:\>nslookup subsurface-divelog.org
Name:    subsurface-divelog.org
Address:  97.120.208.229

C:\>ping subsurface-divelog.org
Reply from 97.120.208.229: bytes=32 time=90ms TTL=55

SYN sent; no SYN-ACK returned.

Thank you.

**Comment by dirkhh** [comment]
looks like the DNS cache held the previous DYNDNS address - I've had this happen before.
I forced it over and it works again.
On my todo list: move the webserver to a static IP address.
