### ISSUE TITLE
Gas switches / current gas missing in UDDF export

### ISSUE THREAD

**Issue by KG32** [Subsurface-divelog/subsurface#4056]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When exporting a UDDF, `<switchmix/>` elements are missing. 

### Operating system:

macOS Sonoma 14.0 (23A344), English

Macbook Pro 16, Apple M1 Pro

### Subsurface version:

5.0.10

Official release

### Steps to reproduce:

- Export dive(s) (in that case from from Shearwater Perdix 2) with gas switches as UDDF
- Open the exported logbook

### Current behavior:

- Gas switches are gone, all dives seem to be on air only
- In the .uddf file there's no `<switchmix/>` elements in respective `<waypoint>` elements
### Expected behavior:

- `<switchmix/>` elements are present in the .uddf file
- gas switches are visible when opening exported UDDF

**Comment by mikeller** [comment]
@KG32: Can you please test with https://github.com/subsurface/nightly-builds/releases/tag/v6.0.5081-CICD-release to verify that the UDDF files produced by Subsurface (now with `<switchmix/>` elements) are correctly parsed by the application you want to use them for?

**Comment by KG32** [comment]
@mikeller seems like the exported UDDF files contain correct `<switchmix/>` elements now. Thanks a lot!
