### ISSUE TITLE
release 6.0.5054 download links offline

### ISSUE THREAD

**Issue by core-code** [Subsurface-divelog/subsurface#4096]
e.g.
https://subsurface-divelog.org/downloads/Subsurface-6.0.5054-CICD-release.dmg
=>
404

**Comment by mikeller** [comment]
It looks like the binaries on the web server have been updated to 5082, but the links on the Current Release page are still pointing to 5054, @dirkhh can you please have a look?

@core-code you can download the binaries for the latest current release (5082) from https://subsurface-divelog.org/downloads/ for the time being.

**Comment by dirkhh** [comment]
webserver stumbled over its feet and lost the updated data for the current release. Please try again.

**Comment by core-code** [comment]
thanks, download works now.

since i am already typing, just FYI the meta-data doesn't line up. CFBundleVersion and CFBundleShortVersionString are stuck at 6.0.5082 while they should be 6.0.5094 - screenshot attached

<img width="254" alt="Screenshot 2024-02-13 at 20 41 04" src="https://github.com/subsurface/subsurface/assets/1261954/c050e15c-06c9-4b92-8f51-a2a2502b157e">

**Comment by dirkhh** [comment]
I noticed that while testing the broken link.
Will fix and replace

**Comment by dirkhh** [comment]
The file has been replaced. Please re-download. My apologies for the mixups.

**Comment by core-code** [comment]
thanks, confirmed fixed

**Comment by core-code** [comment]
@dirkhh on the topic of Mac release abnormalities, why do the disk-images contain the zipped app alongside the non-zipped app?

```ls /Volumes/Subsurface-6.0.5094 
Applications		Subsurface-6.0.5094.zip	Subsurface.app
```

if you make the window wider you see it:


<img width="759" alt="Screenshot 2024-02-15 at 21 25 21" src="https://github.com/subsurface/subsurface/assets/1261954/083d1d3f-2ebe-4d9a-9f7e-895f1b130820">

**Comment by dirkhh** [comment]
I figured out yesterday how to avoid that. So this won't be the case anymore starting with the next one.
Initially the stapling of the notarization failed otherwise.

**Comment by mikeller** [comment]
> Initially the stapling of the notarization failed otherwise.

Need to use iStaples for Mac... 😝
