### ISSUE TITLE
The display of GF low/GF high above the dive profile is wrong/misleading.

### ISSUE THREAD

**Issue by ghost** [Subsurface-divelog/subsurface#4141]
### Describe the issue:

- [ ] Bug
- [x ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

On desktop the values shown above the dive profile are the ones set in Preferences -> Tech setup. But in Extra Info the values imported from the dive computer are shown.

<img width="1097" alt="Subsurface_GF_values" src="https://github.com/subsurface/subsurface/assets/3070848/861237f1-daba-4fb0-8f9e-dc8b6d0e88ad">
 
The same goes for the iOS app where the values from the Settings -> Advanced are shown above the dive profile. I could not find a way to get the value from the dive computer displayed on iOS.

### Operating system:

current mac OS (14.4), current iOS (17.4)

Shearwater Perdix AI, firmware version 93

### Subsurface version:

Mac: 5.0.10
iOS: 6.0.5124

Unknown.

Official releases.

### Steps to reproduce:

1) On dive computer: set values for GF low and GF High
2) On desktop: set values for GF low and GF high in Preferences -> Advanced to  values different to those in the dive computer
3) dive
4) import data from dive computer
5) compare values shown above the dive profile with those in Extra Info

### Current behavior:

The manually set value is shown, actual data from the dive computer are ignored.

### Expected behavior:

GF low and GF high as read from the dive computer should be shown.

**Comment by dirkhh** [comment]
Yes, works as designed. The value above the graph shows the GF used for the calculated ceiling.
