### ISSUE TITLE
iOS app cloud issues

### ISSUE THREAD

**Issue by lhangart** [Subsurface-divelog/subsurface#4154]
### Describe the issue:

- [ ] Bug

### Issue long description:
Current iOS app failed to sync data with cloud. Deleted app and app data and reinstalled app. Now, I cannot log in any longer. Same email/password combination that works on the MacOS desktop app raises 'incorrect email / password combination' error. Resetting password did not fix the issue.

### Operating system:
iOS 17.4.1

### Subsurface version:
6.0.5.5124

### Steps to reproduce:
Deleted app and app data and reinstalled app, reset password

**Comment by dirkhh** [comment]
please try to log into the cloud and reproduce the failure. Then switch to no-cloud mode (in order to get to the main menu) and send a support request from within the app. That way I'll get relevant logs that might help understand what's going wrong.

The most common issue are incorrectly spelled email addresses (I had people yell at me for doubting that they knew their own email address, only to later say "you know what, never mind, I fixed it) and subtly different behavior with special characters in the password -- I highly recommend to just use ascii letters and numbers.

**Comment by lhangart** [comment]
Hi Dirk,

I would never yell at open source developers as I really appreciate the good work you are all doing. Misspelled email and password was my first suspicion, too, but I copied and pasted both from the iOS keychain and it worked for the desktop app but not for iPhone app. So this is how things resolved: I tried again this morning and the app got hung up after clicking the login bottom. I then restarted my iPhone and after the restart, everything seemed to work. The only other thing I did was chaining the keyboard language from German to English (there are no non-ASCII characters in either the password or username, and I also used copy/paste from the keychain). So there is that… I still can send you the request for the request for the log data, if it was helpful. I closed the issue on GitHub.

Since I have you on the horn: Is there a way to change the default liter volume of a tank? The app gives 9.7l for an HP80 but the most common HP80 tank used around here (Faber) has a volume of 10.2l. 

And last, a feature request: since most divers frequently dive with the same few gear configurations, would it be possible to implement equipment presets/configs that populate weights, suit and tanks upon selection?

Thanks again,

Lars

**Comment by dirkhh** [comment]
I'm glad it worked out.
The only log that would have been interesting would have been a log of a failure. Now that it works, there won't be anything interesting in there.

You can simply create your own tank that matches what you need. Please do so in the desktop app and save at least one dive using that tank. After you sync this with the phone, that tank will be available on the phone in the dropdown as well.

Copying default equipment / people is easily possible in the desktop version. Trying to do this in the mobile version is beyond the skills of the current set of developers, I think.

**Comment by lhangart** [comment]
Hi Dirk,

Thanks for your explanations. I managed to make my own tank and it synced to the phone and also discovered the ‘copy dive components’ feature 🙈

Best,

Lars

**Comment by lhangart** [comment]
Hi Dirk,

The synch issue occurred again, but only when my iPhone was connected to the local WiFi network. After I switched to 3G, it synched again.. I submitted the logs from within the app.

Best,

Lars

**Comment by mikeller** [comment]
Hi Lars.

> The synch issue occurred again, but only when my iPhone was connected to the local WiFi network. After I switched to 3G, it synched again.. I submitted the logs from within the app.

What kind of WiFi network are you using? Residential broadband with access point / public WiFi / corporate WiFi?
From your description it looks like the problem could be overly aggressive firewalling / misconfiguration / general access limitations between the WiFi network and the internet.

**Comment by lhangart** [comment]
Hi Dirk,

It is a corporate/edu network (The Scripps Research Institute). Also, our IT is currently redesigning our WiFi architecture to improve security, so it’s quite possible that something was blocked by this network. What port are you using for the sync?

L

**Comment by Subsurface-divelog** [comment]
It's https. My guess is that they are using a man in the middle reverse proxy and that Subsurface says "no thank you" to that 

Generally I recommend not to use any corporate resources for non corporate purposes. Separate devices, separate infrastructure. 

IT organizations are in the business of assuming that they own everything and control everything and that anything they don't know is by definition evil and needs to be taken over. I generally decline to allow IT controlled devices onto my personal networks, nor do I connect personal devices to corporate networks. 

(and yes, ironically I work in a gigantic IT organization of some 20k people) 

/D
