### ISSUE TITLE
Errors with online storage

### ISSUE THREAD

**Issue by nsmtbkr** [Subsurface-divelog/subsurface#4212]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Subsurface app does not appear to push latest dive (today) to online storage.  Tried multiple times with no success.
Subsurface website SSL certificate has expired, requires bypassing browser insecurity warnings to log in
Subsurface windows app tried multiple cloud storage locations, then throws a "Failure taking cloud storage online" error.

### Operating system:

iOS for app
Windows 11 Pro

### Subsurface version:

6.0.5144

**Comment by mikeller** [comment]
Thanks for reporting this.

Looks like it has already been fixed: https://groups.google.com/g/subsurface-divelog/c/P3lngV_1FOc/m/gto6zFy_DwAJ

**Comment by nsmtbkr** [comment]
Confirmed fixed.  Thanks!
