### ISSUE TITLE
Map is not displaying

### ISSUE THREAD

**Issue by Julaye** [Subsurface-divelog/subsurface#4215]
### Describe the issue:

- [ X ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Since few development release, the google map is not displaying.

### Operating system:
MacOS 14.5 on MacBook Air M2

### Subsurface version:
6.0.5190-CICD-Release from subsurface daily 
Problem start with the 6.0.5185-CICD-Release, perhaps before.

### Steps to reproduce:
Launch the software, map is not displaying

### Current behavior:
Google map view is blank

### Expected behavior:
Google map view on the dive site

### Additional information:
Snapshot

### Mentions:
<img width="1470" alt="Capture d’écran 2024-05-28 à 08 37 03" src="https://github.com/subsurface/subsurface/assets/35028797/d198f70d-18c7-4372-80b2-bf4cf74b8ef1">

**Comment by mikeller** [comment]
@notrege: It looks like this problem was introduced when we switched to using Qt 5.15.13 in #4180. Are you able to test and see if you can get a build of Qt 5.15.13 that can build a working version of the Google maps plugin? It looks like it gets built as it displays the minimap and buttons, but it does not show the full map.

**Comment by notrege** [comment]
I'm away for the week, but will take a look when I get home.

**Comment by notrege** [comment]
It looks like we are building a debug version of the plugin (libqtgeoservices_googlemaps_debug.dylib) and that doesn't get deployed.    I added a potential fix for this in https://github.com/subsurface/subsurface/pull/4224, but am hoping there is a better way to do this.
