### ISSUE TITLE
Subsurface goes into an infinite loop when drilling into a Garmin MK3i dive with multiple transmitters 

### ISSUE THREAD

**Issue by bwong2132** [Subsurface-divelog/subsurface#4225]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

In Subsurface 6.0.5194 CICD Release, I was able to import in dives from a Garmin MK3i with multiple T2 transmitters (3). However, after importing in, subsurface goes into an infinite loop when I import and drill into dives with multiple transmitters. Subsurface works as expected when I only import Garmin MK3i dives with a single transmitter. 

### Operating system:

macOS Sonoma 14.4.1

MacBook Air M2

### Subsurface version:

6.0.5194-CICD-Release

older versions cannot import Garmin MK3i dives

Official

### Steps to reproduce:

1) import Garmin MK3i FIT files 
2) go into the dives 

### Current behavior:

Subsurface goes into infinite loop when drilling into dives with multiple transmitters. Subsurface works as expected when I only import MK3i dives with a single transmitter.

### Expected behavior:

No infinite loop

### Additional information:

Yes, I have both Garmin MK3i dives with a single transmitter and others with multiple transmitters. I will upload them in a follow up. I am currently unable to upload files in this ticket. 

### Mentions:

@mikeller

**Comment by bwong2132** [comment]
2024-05-29-09-22-06.txt - has multiple transmitters and will result in an infinite loop
[2024-05-29-09-22-06.txt](https://github.com/user-attachments/files/15514590/2024-05-29-09-22-06.txt)

2024-05-25-11-03-57.txt has a single transmitter and does not result in an infinite loop
[2024-05-25-11-03-57.txt](https://github.com/user-attachments/files/15514607/2024-05-25-11-03-57.txt)

**Comment by mikeller** [comment]
Unfortunately I can not reproduce this behaviour - importing 2024-05-29-09-22-06.txt on MacOS using 6.0.5194, and then opening the dive is working just fine for me.

Can you try to reproduce this by running Subsurface with logging enabled by running `/Applications/Subsurface.app/Contents/MacOS/Subsurface -v -v -v` from the console, reproducing the problem, and then posting the console output?

You can also check if the lockup is dependent on your preference settings by running Subsurface for a different user with `/Applications/Subsurface.app/Contents/MacOS/Subsurface --user=test` and then trying to reproduce.

**Comment by bwong2132** [comment]
Hi Mike - here is the log 

[log.txt](https://github.com/user-attachments/files/15520202/log.txt)

I have narrowed the steps to reproduce the problem. 
- import multiple Garmin MK3i files - OK 
- drill into each dive - OK 
- select the multiple dives so that you can create a trip -- hang. 

My apologies. Drilling into a dive worked. However, I got the infinite loop when I selected multiple files. 

Thanks for looking into this.

**Comment by bwong2132** [comment]
In case you need some additional files, here are three 
[2024-05-25-11-03-57.txt](https://github.com/user-attachments/files/15520214/2024-05-25-11-03-57.txt)
[2024-05-29-09-22-06.txt](https://github.com/user-attachments/files/15520215/2024-05-29-09-22-06.txt)
[2024-05-29-10-58-14.txt](https://github.com/user-attachments/files/15520216/2024-05-29-10-58-14.txt)

05-25 file has one working transmitter and one missing transmitter (transmitter not within range). The two 05-29 files have three T2 transmitters.

**Comment by mikeller** [comment]
Ok, I had a poke at this:
- the problem does not manifest under Linux;
- on MacOS, it manifests when selecting multiple dives, even if these do not have any sensor information, but it does not happen for all dives;
- it does not happen for versions prior to https://github.com/subsurface/nightly-builds/releases/tag/v6.0.5159-CICD-release

@notrege unfortunately this looks like another problem that started when we updated Qt for the MacOS build. :-(
Do you have time to look into this?

**Comment by notrege** [comment]
Hopefully during the week.   🤞

**Comment by notrege** [comment]
I think this was fixed with https://github.com/subsurface/subsurface/pull/4224.    Can you please download https://github.com/subsurface/subsurface/suites/24388310471/artifacts/1556120159 and see if this works for you?
<img width="1133" alt="Screen Shot 2024-06-01 at 8 44 59 AM" src="https://github.com/subsurface/subsurface/assets/32236882/0c9c7a9b-20e8-469a-b527-ca30ca41f6ab">

**Comment by bwong2132** [comment]
Yes - https://github.com/subsurface/subsurface/suites/24388310471/artifacts/1556120159 works. I was able to select multiple Garmin MK3i dives, create a trip, zoom around, etc.  Thanks @notrege  and @mikeller

**Comment by notrege** [comment]
Excellent - thanks for testing this.
