### ISSUE TITLE
GF Low/High will reset to default value in "Edit dive in planner" after restarting Subsurface

### ISSUE THREAD

**Issue by cchsieh** [Subsurface-divelog/subsurface#4240]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I plan a dive, set the GF low/high which is different from the default value in Preferences. 
I save everything, and close the Subsurface. 
Then, I open Subsurface again, and choose "Edit dive in planner", and the GF low/high reset to the default value.

### Operating system:

Windows 11 Chinese Tranditional

### Subsurface version:

6.0.5204-CICD-release

official release

### Current behavior:

GF low/high will reset to defalut value in "Edit dive in planer" after restarting the Subsurface program.

### Expected behavior:

The GF low/high would be the one I set, not default value.

**Comment by mikeller** [comment]
In Subsurface there are two different gradient factor settings, and it's important to keep in mind where they are used:

1. there is one gradient factor setting in the Preferences / Tech setup. This is used to calculate the calculated ceiling that is shown in the dive profile when NOT in the planner:
![image](https://github.com/subsurface/subsurface/assets/4742747/9ec3ac60-8859-4449-aa41-856019d4b1e5)


2. there also is the gradient factor that can be set on the planner page, and is used to calculate the decompression schedule when planning a dive. But this is not persisted with the dive when it is saved, so when looking at a planned dive in the dive list, the setting in 1. is applied for the calculated ceiling.

**Comment by cchsieh** [comment]
Thanks for your replying so quickly.

My preferences:
![螢幕擷取畫面 2024-06-07 101812](https://github.com/subsurface/subsurface/assets/1562966/5c78b3af-acd8-443d-a75c-8c82181f4f0a)

I create a new Plan dive, and modify GF low/high and save.
![螢幕擷取畫面 2024-06-07 101941](https://github.com/subsurface/subsurface/assets/1562966/1b61001b-82c3-4abd-b9cb-6afbd15421d2)

Than I reopen it by "Edit dive in planner" without exit Subsurface progrm.
![螢幕擷取畫面 2024-06-07 102040](https://github.com/subsurface/subsurface/assets/1562966/5510b325-a488-4de0-a3e1-e4daedbfbd99)

The setting of GF low/high is the same as what I modified last time.
![螢幕擷取畫面 2024-06-07 102004](https://github.com/subsurface/subsurface/assets/1562966/c8fa075b-6452-431c-94b4-b53be1d99100)

I shutdown/exit Subsurface program fully and start Subsurface again, and reopen the dive plan by "Edit dive in planner". The setting of GF low/high will change to the default value in preference.
![螢幕擷取畫面 2024-06-07 102053](https://github.com/subsurface/subsurface/assets/1562966/9a6e1fb4-259d-4a31-b246-e19934843a34)

It is weired for me if I planed and saved a dive last night and open it this morning but the setting is changed without any warning. 
 
Sorry for my bad English.

**Comment by cchsieh** [comment]
BTW, "water type" has the same behavior. I set "water type" to "Sea water" and save the plan. After I exit Subsurface and then re-open it, the water type setting will change back to "Fresh water"

**Comment by mikeller** [comment]
Yes, as I said in my first response, the gradient factor used for planning is NOT saved with the dive - the same as all the other planner settings that are not stored either. So when you re-edit the dive in planner, the gradient factor that is configured in planner is used. And this is read from the preferences at startup.
The fact that the water type is not stored when saving a dive in planner seems to be a bug though.

**Comment by cchsieh** [comment]
I see. Thanks.
