### ISSUE TITLE
subsurface-divelog.org certificate has expired, open cloud storage not working.

### ISSUE THREAD

**Issue by orderoftheflame** [Subsurface-divelog/subsurface#4270]
Hiya, long term user, first time issue raiser.

I noticed I couldn't connect to the cloud via the application, and upon further investigation it looks like the subsurface-divelog.org certificate expired today.

I'm not sure if this is related to the cloud not working for sure, but it seems like a logical explaination.

<img width="551" alt="image" src="https://github.com/user-attachments/assets/e9b2ca95-aa9a-4c48-9aca-bf79adbf2068">

<img width="661" alt="image" src="https://github.com/user-attachments/assets/33e0100a-a172-4a0c-b733-05edd09247e2">

**Comment by dirkhh** [comment]
should be fixed

**Comment by orderoftheflame** [comment]
All good! Cheers!
