### ISSUE TITLE
UDDF Export: when select "all dives", exported file is empty

### ISSUE THREAD

**Issue by rafsalvioni** [Subsurface-divelog/subsurface#4275]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When export dives to UDDF format and "all files" selection checked, result file is empty

### Operating system:
Ubuntu 22.04.4 LTS

### Subsurface version:
6.0.5230

### Steps to reproduce:
In a opened logbook:
1) Go to File -> Export (Ctrl+E);
2) Select "UDDF" in export format;
3) Select "all dives" in selection box;
4) Press "OK" and choose file location

### Current behavior:
Exported file is empty

### Expected behavior:
Exported file contents should be whole logbook in UDDF format

**Comment by rafsalvioni** [comment]
I try to analyze the code, but I didnt found the issue... I think that is in XSLT transformation

**Comment by mikeller** [comment]
I had a quick check, and with my test logs the UDDF exported just fine when 'all dives' is checked.
So I suspect that some data that you have in at least one of the dives in your log is causing an error and abort during the XSLT transformation.
Did you try running Subsurface with -v -v -v command line arguments and checking if there is anything in the log hinting at where the transformation is failing?

**Comment by rafsalvioni** [comment]
@mikeller Log shows a error in XSLT:

![image](https://github.com/user-attachments/assets/589d2cb8-ee3f-4fd5-a82d-0933c7a42730)

I run Subsurface 6.0.5230 on Linux

**Comment by mikeller** [comment]
@rafsalvioni: Can you please test if the artifacts in #4278 fix this?

**Comment by rafsalvioni** [comment]
> @rafsalvioni: Can you please test if the artifacts in #4278 fix this?

Tested. Fix OK
