### ISSUE TITLE
Filter pre-set does not work with negative criteria

### ISSUE THREAD

**Issue by Patrick-BS** [Subsurface-divelog/subsurface#4277]
When saving filter with negative criteria it shows an error message on opening Subsurface again. The negative createria gets changed to a positive.

### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I use a filter pre-set to filter for cave1 and tech1 dives. I use three tags here: "cave1", "tech1" and for course dives "Ausbildung".
so i use the following filter to identify real cave dives for example:

![grafik](https://github.com/user-attachments/assets/17e66341-a802-4aba-87a9-00854e69f915)

When configured freshly - everything works. But when I save, close subsurface and reopen it, the following error is shown:
![grafik](https://github.com/user-attachments/assets/17888a6a-bd6c-43f4-8b86-6d0b300ebb02)

And the negative criteria got changed:
![grafik](https://github.com/user-attachments/assets/f53b82a1-b2bf-4d66-908f-08400e3d1530)

### Operating system:

Win 11

### Subsurface version:

6.0.5214

### Steps to reproduce:
See description

### Current behavior:
See descripton

### Expected behavior:
Filter pre-sets beeing saved correctly.

**Comment by mikeller** [comment]
This has been fixed in [6.0.5215](https://github.com/subsurface/nightly-builds/releases/tag/v6.0.5215-CICD-release) and later, please use our [latest release](https://www.subsurface-divelog.org/latest-release/?lang=en) (for now).
