### ISSUE TITLE
missing weight type dropdown list

### ISSUE THREAD

**Issue by KimDelmar** [Subsurface-divelog/subsurface#4294]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When adding or editing a "weight" in the equipment tab of a dive, the dropdown menu allowing selection of pre-defined weight "types" is missing/blank.

### Operating system:

Apple MBP 13" M1, macOS Sonoma 14.6.1, English

### Subsurface version:

CICD builds 6.0.5229, 5230 and 5231 work correctly.
CICD builds 6.0.5232, 5233 and the latest 5239 are all buggy.

This appears to be a regression introduced in the 6.0.5232 build.

macOS dmg builds were downloaded from the github/subsurface/nightly-builds repo.

### Steps to reproduce:

Load a divelog with a dive. Go to Equipment tab and add (or edit) a new "weight" by clicking the "+" icon.
click in the "type" column. Text can be entered, but the dropdown list of pre-defined weight types does not appear.

### Current behavior:

The dropdown list of pre-defined and locally-defined weight type is not shown.

### Expected behavior:

The dropdown list of pre-defined and locally-defined weight types should be shown
(eg, integrated, ankle, belt, backplate etc).

### Additional information:

Other similar fields in the equipment tab seem unaffected (eg, the cylinder type dropdown works fine); only the weight type isnt working. As text can be entered manually here (and everything behaves correctly if you do), this is a relatively minor bug.

**Comment by mikeller** [comment]
Confirmed on linux.

@bstoeger this looks like fallout from #4198, based on when it started.

**Comment by KimDelmar** [comment]
Works fine for me in newly minted 6.0.5241. Thanks!
