### ISSUE TITLE
Dive site management - country field

### ISSUE THREAD

**Issue by kluuzna** [Subsurface-divelog/subsurface#4357]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Entry of "Country" field in "Dive site management" is not retained/stored

### Operating system:

Windows 11 Pro OS Build: 22631.4317

Lenovo laptop

### Subsurface version:

6.0.5281

Yes on 6.0.5276 

Official releases

### Steps to reproduce:

1) Click on "globe" - Edit dive site
2) Enter country name in "Country" filed
3) Click on "Done"
4) Returned to dive list, but country not shown

### Current behavior:

Entered country name is not retained/stored

### Expected behavior:

Country name to be stored as was previously the case

**Comment by mikeller** [comment]
@kluuzna: Can you please test if this is fixed for you in https://github.com/subsurface/subsurface/suites/30407436781/artifacts/2136048667?

**Comment by kluuzna** [comment]
Many thanks Michael, fix worked for me!

**Comment by PT1975** [comment]
Using v5276 on Windows 11, issue is readily repeatable using the steps to reproduce in the original bug report. This is when editing or creating a new dive site. Sometimes, it works as intended but I'm unable to determine the difference (tried changing other parameters such as coordinates without success).
