### ISSUE TITLE
Dives downloaded from Garmin Descent x50i have wrong timestamp

### ISSUE THREAD

**Issue by WetsuitSeasoning** [Subsurface-divelog/subsurface#4401]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When downloading a dive from the Garmin Descent x50i, the imported dive timestamp does not match the start or end time of the dive on the dive computer. It is off by 5 hours.

### Operating system:
Linux Mint 21.3

### Subsurface version:
Subsurface 6.0.5301-CICD-Release

### Steps to reproduce:
Complete a dive using the Garmin Descent x50i.
Connect the dive computer using the Garmin USB cable.
Select Import from Dive Computer in Subsurface.
Use these settings:
- Vendor: Garmin
- Dive Computer: Descent Mk2(i)/Mk3(i)

Navigate to the mount point of the Descent x50i in the file system.
Select Download
Compare the timestamp in Subsurface to the Start/End timestamps on the dive computer.

### Current behavior:
The imported dive in Subsurface is 5 hours later than when it actually occurred.

### Expected behavior:
The imported dive in Subsurface accurately reflects the start/end time of the dive

### Additional information:
Zip archive containing FIT files attached.
[Garmin Descent x50i FIT files.zip](https://github.com/user-attachments/files/18241313/Garmin.Descent.x50i.FIT.files.zip)

**Comment by mikeller** [comment]
Closed by https://github.com/subsurface/libdc/pull/69, available in https://subsurface-divelog.org/latest-release/
