### ISSUE TITLE
Clicking "Log > Add dive" causes window to freeze

### ISSUE THREAD

**Issue by Alexander-Wilms** [Subsurface-divelog/subsurface#565]
This happens with a Flatpak build of the master branch using this manifest: https://github.com/Alexander-Wilms/flathub/blob/org.subsurface_divelog.Subsurface/org.subsurface_divelog.Subsurface.json

[gdb-subsurface.txt](https://github.com/Subsurface-divelog/subsurface/files/1290844/gdb-subsurface.txt)

**Comment by neolit123** [comment]
thanks for the report. i've notified the mailing list about this.

**Comment by Alexander-Wilms** [comment]
Thanks! It seems like that commit broke the build, though: https://travis-ci.org/Subsurface-divelog/subsurface/builds/276276872?utm_source=github_status&utm_medium=notification

**Comment by dirkhh** [comment]
Yes and no. There is one test (TestParse) that for odd reasons doesn't appear to be 100% stable.
The build is fine, but the test failed once again with a spurious po2 attribute

**Comment by dirkhh** [comment]
Restarted the travis job and it now passes
